# common

common:
  subrosa:
    username: subrosa
  users:
    to_remove:
      - games
      - irc
      - list
      - news
      - proxy
      - uucp
  groups:
    to_remove:
      - games
      - irc
      - list
      - news
      - proxy
      - uucp
  apt:
    cache_valid_time: 3600

# sshd

sshd:
  package: openssh-server
  version: 1:6.0p1-4+deb7u2
  config:
    port: 22
    enable_pam_auth: 'no'
    enable_password_auth: 'no'
    enable_pub_key_auth: 'yes'

# nginx

nginx:
  version: 1.6.3-1~wheezy

# openssl

openssl:
  package: openssl
  version: 1.0.1e-2+deb7u16
  self_signed_certs:
    dir_path: /etc/ssl/selfsigned
    key_path: /etc/ssl/selfsigned/key
