common:
  users:
    to_remove:
      - games
      - irc
      - list
      - news
      - proxy
      - uucp
  groups:
    to_remove:
      - games
      - irc
      - list
      - news
      - proxy
      - uucp
