---

- hosts: all
  sudo: True
  gather_facts: True
  tasks:
    - name: main | site.yml | group hosts by distribution / version
      group_by: key=os_{{ ansible_distribution }}{{ ansible_distribution_version|int }}
      changed_when: False # Don't ever report a change here

- hosts: os_Debian7
  sudo: True
  gather_facts: True
  roles:
   - common
   - encfs
   - openssl
   - sshd
   - mail
   - nginx
   - owncloud
