---
  - name: nginx | nginx_os_debian7.yml | install nginx
    apt: name={{ nginx.package }}={{ nginx.version }} state=present
    tags: nginx

  - shell: ls -1 /etc/nginx/sites-available
    register: nginx_sites_available_contents

  - name: nginx | nginx_os_debian7.yml | remove all nginx site configurations in sites-available
    file: path=/etc/nginx/sites-available/{{ item }} state=absent
    with_items: nginx_sites_available_contents.stdout_lines
    notify:
      - reload nginx
    tags: nginx

  - shell: ls -1 /etc/nginx/sites-enabled
    register: nginx_sites_enabled_contents

  - name: nginx | nginx_os_debian7.yml | remove all nginx site configurations in sites-enabled
    file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
    with_items: nginx_sites_enabled_contents.stdout_lines
    notify:
      - reload nginx
    tags: nginx

  - name: nginx | nginx_os_debian7.yml | remove default configuration
    file: path=/etc/nginx/conf.d/default.conf state=absent
    notify:
      - reload nginx
    tags: nginx

  - name: nginx | nginx_os_debian7.yml | ensure nginx configuration
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf group=root owner=root
    notify:
      - restart nginx
    tags: nginx

  - name: nginx | nginx_os_debian7.yml | ensure nginx ssl directory exists
    file: path=/etc/nginx/ssl state=directory
    tags: nginx
